### ISSUE TITLE
remove duplicated bib items doesn't work

### ISSUE THREAD

**Issue by anhvt2** [klb2/bibtex-tools#2]
I tried to combine 2 bibtex files but the entries were renamed rather than removed. This results in a (much) longer bib file with different entry names for the same citation.

**Comment by klb2** [comment]
Thanks for filing the bug report. I will have a look into it

**Comment by klb2** [comment]
Right now, there is no check whether a citation already exists in terms of the same content. There is only a duplicate check for the same IDs. However, this is an important feature and I will work on this.

**Comment by klb2** [comment]
I have added a new functionality that automatically detects duplicates based on the content (similar title, ...). It will automatically be run after loading a bib file.

This feature is already active on the `master` branch version and will be released via PyPI with the next release version.

**Comment by klb2** [comment]
I have released a new version (0.5.0) on PyPI. You can find it here: https://pypi.org/project/bibtextools/ and you should be able to install it using
```bash
pip install --upgrade bibtextools
```

**Comment by anhvt2** [comment]
Thanks for updating and providing the tool. I will test out the new release then.

**Comment by klb2** [comment]
There might be some false positives. In that case, please open a new issue and provide some examples which are wrongly classified as duplicate.
